### ISSUE TITLE
does MLstudio write R code?

### ISSUE THREAD

**Issue by ran88dom99** [RamiKrispin/MLstudio#3]
https://alternativeto.net/list/2063/guis-to-save-from-typing-r-code

**Comment by RamiKrispin** [comment]
The package is for now only a GUI, but hopefully in the future, it will have the ability to retrieve the code from the models or any other functions

**Comment by rhoconlinux** [comment]
+1 for this, it would be very useful

**Comment by RamiKrispin** [comment]
I am currently working on another project, but the plan is to re-alive this project around June. The plan to add this functionality to this package
